### ISSUE TITLE
THE ROADMAP: Everything we want to change for this release: 

### ISSUE THREAD

**Issue by alexlenail** [fraenkel-lab/OmicsIntegrator2#1]
@divyaramamoorthy @AmandaKedaigle 

## New in this version
- [x] Python 3
- [x] Use Garnet2
- [x] Use Ludwig's PCSF
- [x] Keep in mind GSSLR (Alex)
- [x] Clean things up

## Safe to Remove: 
- [x] Cross validation code
- [x] Shuffle Prizes 
- [x] Support for Cytoscape 2.8
